### ISSUE TITLE
Script should exit if checksum fails

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#1]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L50

This line just runs the check, but there I see no error exit if the checksum does not match.
Ideally, the script would attempt a re-download on a checksum mismatch and fail if that still not matches.
Also a failed download (e.g. if the remote website is inaccessible) should cause an error exit.

**Comment by vgnshm** [comment]
Exit code added in 2nd commit
