### ISSUE TITLE
Adjust choice of SIMD level in gromacs for Owl's Nest hardware

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#10]
Please note the following message in the gromacs log file
```
Highest SIMD level supported by all nodes in run: AVX2_256
SIMD instructions selected at compile time:       SSE4.1
This program was compiled for different hardware than you are running on,
which could influence performance.
```
So it seems we need some proper benchmark numbers to determine which choice is faster and by how much.

**Comment by vgnshm** [comment]
Previous gromacs 2021.4 versions in Owl's nest was compiled with `SSE4.1`  SIMD. Code is now compiled with highest SIMD level supported by all nodes in run: `AVX2_256`.
