### ISSUE TITLE
Always wipe out source and install folders

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#2]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L54

While caching the download is a good idea, caching the extracted source tree is not.
Instead, any source trees (also from older versions if they exist)  should be wiped out completely.
Some for the installation folder. Only if those are deleted, is it possible to have a completely reproducible procedure.

**Comment by vgnshm** [comment]
Comment taken constructively. Changes have been done in 2nd commit
