### ISSUE TITLE
Load specific versions of modules

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#3]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L61

To achieve the goal of reproducible results, it is necessary to load specific versions of module files.
When loading the default the result of the script can change if the defaults are changed. That would be undesired behavior.

**Comment by vgnshm** [comment]
Only latest and necessary modules are loaded in 2nd commit. Check code and revert back.
