### ISSUE TITLE
Always build new executables, don't use "make install" with LAMMPS

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#4]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L75

For the same reasons as mentioned in #2 and #3, the build folder should always be deleted. There should be a different build folder for each "variant" of LAMMPS.

The "make install" target was added to LAMMPS mostly for package managers (e.g. Ubuntu or RedHat/Fedora). For the HPC clusters we don't really need this. More importantly, your method requires to keep a copy of the sources around, which is **highly** undesirable.

Please check out what the contents of the existing LAMMPS modules are and recreate that by copying over selected files and folders and the LAMMPS executables. Executables that do not have the "machine" extension are taken from  standard "mpi" machine compilation.

**Comment by vgnshm** [comment]
The **highly** undesirable Traditional 'make install' has been replaced with 'cmake --build'
