### ISSUE TITLE
Enable more packages

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#5]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#LL79C2-L79C3

The "most" preset, is only a starting point. There are plenty more packages that can be enabled. You should try as many as possible. Check out the existing 29Sep2021 version installation. If you run `lmp_mpi -h` it should print which packages are included in that version. There should be even more packages available in the latest version.

**Comment by vgnshm** [comment]
More packages have been enabled based on last available lammps/29Sep2021 module. 'ML-QUIP' shows library '_gfortran_' library conflict warnings. commented out for now
