### ISSUE TITLE
Use CUDA mode for GPU package

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#6]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L89

The GPU package version of LAMMPS should be compiled using `-DGPU_API=cuda -DGPU_PREC=mixed -DGPU_ARCH=sm_60` to match the GPU hardware we have on the "large" queue nodes.

**Comment by vgnshm** [comment]
The mentioned flags have been incorporated into code.

**Comment by akohlmey** [comment]
However, compilation is not performed and the lmp_gpu executable not included in the installation folder.

**Comment by vgnshm** [comment]
A test script which produces lmp_gpu executable is committed again on April 4,2023
