### ISSUE TITLE
Compile and install KOKKOS version with CUDA/GPU suppot

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#7]
https://github.com/vgnshm/templesoftware/blob/dcb5ff039261be280fcab769fbe367dc35c3e395/scripts/lammps-install.sh#L93

The script does not (yet) build and provide a KOKKOS package version. This needs to be added.

**Comment by vgnshm** [comment]
'-D PKG_KOKKOS=on ' is set in cmake
