### ISSUE TITLE
Broken gromacs install script

### ISSUE THREAD

**Issue by akohlmey** [vgnshm/templesoftware#9]
https://github.com/vgnshm/templesoftware/blob/c7fdbe9ce1d37fec4c0d9048f109f2ec2dc8c138/scripts/gromacs-install.sh#L142
https://github.com/vgnshm/templesoftware/blob/d6eac1ae160e875eef34a8462200769b352143b5/scripts/gromacs-install.sh#L143
https://github.com/vgnshm/templesoftware/blob/c7fdbe9ce1d37fec4c0d9048f109f2ec2dc8c138/scripts/gromacs-install.sh#L145

The three lines above are the cause for the error.

**Comment by akohlmey** [comment]
Since it is no longer possible to build standalone "mdrun" executables, those copy commands need to preserve the command names, i.e. gmx_mpi, gmx_gpu, gmx_mpi_d
gmx_gpu probably needs to be build with `-DBUILD_SHARED_LIBS=off` to avoid library conflicts with `gmx_mpi` yet properly support CUDA.

**Comment by vgnshm** [comment]
Gromacs script update with the requested approach: copy commands  now preserve the command names, i.e. gmx_mpi, gmx_gpu, gmx_mpi_d. 
gmx_gpu  is built now with `-DBUILD_SHARED_LIBS=off` to avoid library conflicts with `gmx_mpi `
